name: Reporte de Análisis SAST (CodeQL)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript  

      - name: Ejecutar análisis CodeQL
        uses: github/codeql-action/analyze@v3
